export {
  // primitives
  MAX_ID_LENGTH,
  MAX_PLATE_LENGTH,
  MAX_REFERENCE_NUMBER_LENGTH,
  MAX_RELATIVE_PATH_LENGTH,
  MAX_STORAGE_ROOT_KEY_LENGTH,
  caseIdSchema,
  caseStageSchema,
  caseStatusSchema,
  caseTypeSchema,
  entityVersionSchema,
  idSchema,
  insurerClaimNumberSchema,
  insurerIdSchema,
  localDateSchema,
  nonEmptyStringSchema,
  notificationFormNumberSchema,
  officeCaseNumberSchema,
  plateNumberSchema,
  relativePathSchema,
  serviceIdSchema,
  storageRootKeySchema,
  userIdSchema,
  utcDateTimeSchema,
  type CaseStageDto,
  type CaseStatusDto,
  type CaseTypeDto,
  type EntityVersionDto,
  type LocalDateDto,
  type OfficeCaseNumberDto,
  type PlateNumberDto,
  type UtcDateTimeDto,
  // errors
  API_ERROR_CODES,
  MAX_REPORTED_UNKNOWN_KEYS,
  apiErrorCodeSchema,
  apiErrorSchema,
  fieldErrorSchema,
  zodErrorToApiError,
  type ApiError,
  type ApiErrorCode,
  type FieldError,
  // envelope
  failureEnvelopeSchema,
  responseMetaSchema,
  successEnvelopeSchema,
  type FailureEnvelope,
  type ResponseMeta,
  type SuccessEnvelope,
  // pagination
  DEFAULT_PAGE,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE,
  MAX_PAGE_SIZE,
  SORT_DIRECTIONS,
  SORT_FIELDS,
  pageInfoSchema,
  pageSchema,
  pageSizeSchema,
  pageSizeWithDefaultSchema,
  pageWithDefaultSchema,
  sortDirectionSchema,
  sortFieldSchema,
  type PageInfo,
  type SortDirection,
  type SortField,
  // routes (base)
  API_V1_BASE,
  API_VERSION,
  HEALTH_ROUTE,
} from './common/index.js'

export {
  HEALTH_STATUSES,
  healthResponseSchema,
  healthStatusSchema,
  type HealthResponse,
  type HealthStatus,
} from './health/index.js'

export {
  // cases routes
  CASES_ROUTE,
  CASE_DETAIL_ROUTE,
  // cases query
  MAX_SEARCH_LENGTH,
  casesQuerySchema,
  searchSchema,
  type CasesQuery,
  type CasesQueryInput,
  // cases dto
  caseDetailParamsSchema,
  caseDetailResponseSchema,
  caseDetailSchema,
  caseListItemSchema,
  caseListResponseSchema,
  type CaseDetail,
  type CaseDetailParams,
  type CaseDetailResponse,
  type CaseListItem,
  type CaseListResponse,
  // cases commands
  CASE_UPDATABLE_FIELDS,
  IDEMPOTENCY_KEY_HEADER,
  caseCreateRequestSchema,
  caseUpdateRequestSchema,
  idempotencyKeySchema,
  type CaseCreateRequest,
  type CaseCreateRequestInput,
  type CaseUpdateRequest,
  // cases mappers
  caseCoreToDetail,
  caseCoreToListItem,
  caseDetailToCaseCore,
} from './v1/cases/index.js'

export {
  EXPERTS_REFERENCE_ROUTE,
  INSURERS_REFERENCE_ROUTE,
  SERVICES_REFERENCE_ROUTE,
  USERS_REFERENCE_ROUTE,
  expertsReferenceResponseSchema,
  insurerReferenceSchema,
  insurersReferenceResponseSchema,
  serviceReferenceSchema,
  serviceAgreementEvaluationSchema,
  servicesReferenceQuerySchema,
  servicesReferenceResponseSchema,
  userReferenceSchema,
  usersReferenceResponseSchema,
  type ExpertsReferenceResponse,
  type InsurerReference,
  type InsurersReferenceResponse,
  type ServiceReference,
  type ServiceAgreementEvaluation,
  type ServicesReferenceResponse,
  type ServicesReferenceQuery,
  type ServicesReferenceQueryInput,
  type UserReference,
  type UsersReferenceResponse,
} from './v1/references/index.js'

export {
  // agent routes + headers
  AGENT_CLAIM_ROUTE,
  AGENT_JOB_HEARTBEAT_ROUTE,
  AGENT_JOB_RESULT_ROUTE,
  AGENT_JOB_EXTRACTION_CHUNKS_ROUTE,
  AGENT_JOB_OCR_CHUNKS_ROUTE,
  AGENTS_ROUTE,
  AGENT_DETAIL_ROUTE,
  AGENT_ID_HEADER,
  AGENT_SECRET_HEADER,
  // agent enums + dto
  JOB_TYPES,
  JOB_STATUSES,
  JOB_TARGET_TYPES,
  JOB_PAYLOAD_KINDS,
  jobTypeSchema,
  jobStatusSchema,
  jobTargetTypeSchema,
  jobPayloadSchema,
  fileOperationJobPayloadSchema,
  fileOperationCleanupJobPayloadSchema,
  pdfTextExtractionJobPayloadSchema,
  policyOcrJobPayloadSchema,
  claimedJobSchema,
  claimResponseSchema,
  heartbeatResponseSchema,
  jobResultResponseSchema,
  agentSchema,
  agentRegisterResponseSchema,
  agentResponseSchema,
  agentsListResponseSchema,
  jobParamsSchema,
  agentParamsSchema,
  type JobType,
  type JobStatus,
  type JobTargetType,
  type JobPayload,
  type ClaimedJob,
  type ClaimResponse,
  type HeartbeatResponse,
  type JobResultResponse,
  type Agent,
  type AgentRegisterResponse,
  type AgentResponse,
  type AgentsListResponse,
  type JobParams,
  type AgentParams,
  // agent commands
  RESULT_OUTCOMES,
  FILE_OPERATION_RESULT_PHASES,
  fileOperationResultSchema,
  jobResultRequestSchema,
  agentRegisterRequestSchema,
  agentUpdateRequestSchema,
  type ResultOutcome,
  type FileOperationResult,
  type JobResultRequest,
  type JobResultRequestInput,
  type AgentRegisterRequest,
  type AgentUpdateRequest,
  JOB_PROGRESS_PHASES,
  jobHeartbeatRequestSchema,
  type JobHeartbeatRequest,
} from './v1/agent/index.js'

export {
  CASE_WORKSPACE_PLANS_ROUTE,
  CASE_WORKSPACE_PLAN_ROUTE,
  CASE_WORKSPACE_APPROVE_ROUTE,
  WORKSPACE_PROVISIONING_STATUSES,
  workspaceProvisioningStatusSchema,
  caseWorkspaceSubdirectoriesSchema,
  workspacePlanRequestSchema,
  workspaceApproveRequestSchema,
  workspaceProvisioningSchema,
  workspaceProvisioningResponseSchema,
  workspacePlanParamsSchema,
  workspaceProvisioningParamsSchema,
  type WorkspacePlanRequest,
  type WorkspaceApproveRequest,
  type WorkspaceProvisioning,
  type WorkspaceProvisioningResponse,
  type WorkspaceProvisioningStatus,
  type WorkspacePlanParams,
  type WorkspaceProvisioningParams,
} from './v1/workspace/index.js'

export {
  CASE_FILE_OPERATION_PLAN_ROUTE,
  CASE_FILE_OPERATION_ROUTE,
  CASE_FILE_OPERATION_APPROVE_ROUTE,
  CASE_FILE_OPERATION_CANCEL_ROUTE,
  FILE_OPERATION_TYPES,
  FILE_OPERATION_STATUSES,
  FILE_OPERATION_STRATEGIES,
  FILE_OPERATION_CLEANUP_STATES,
  fileOperationTypeSchema,
  fileOperationStatusSchema,
  fileOperationStrategySchema,
  fileOperationCleanupStateSchema,
  logicalStorageReferenceSchema,
  fileOperationPlanRequestSchema,
  fileOperationApproveRequestSchema,
  fileOperationCancelRequestSchema,
  fileOperationSchema,
  fileOperationResponseSchema,
  fileOperationPlanParamsSchema,
  fileOperationParamsSchema,
  type FileOperationType,
  type FileOperationStatus,
  type FileOperationStrategy,
  type FileOperationCleanupState,
  type LogicalStorageReference,
  type FileOperationPlanRequest,
  type FileOperationApproveRequest,
  type FileOperationCancelRequest,
  type FileOperation,
  type FileOperationResponse,
  type FileOperationPlanParams,
  type FileOperationParams,
} from './v1/file-operations/index.js'

export {
  // document routes + scopes
  DOCUMENTS_ROUTE,
  DOCUMENT_DETAIL_ROUTE,
  PHOTOS_ROUTE,
  PHOTO_DETAIL_ROUTE,
  DOCUMENT_REGISTER_SCOPE,
  PHOTO_REGISTER_SCOPE,
  // document enums + primitives
  DOCUMENT_STATUSES,
  SOURCE_TYPES,
  MAX_BYTE_SIZE,
  MAX_DOCUMENT_TYPE_LENGTH,
  MAX_FILE_NAME_LENGTH,
  byteSizeSchema,
  documentStatusSchema,
  documentTypeSchema,
  extensionSchema,
  mimeTypeSchema,
  originalFileNameSchema,
  sha256HexSchema,
  sourceTypeSchema,
  type DocumentStatus,
  type SourceType,
  // document dto
  documentSchema,
  documentDetailSchema,
  documentVersionSchema,
  photoSchema,
  duplicateSignalSchema,
  documentRegisterResponseSchema,
  photoRegisterResponseSchema,
  documentsListResponseSchema,
  documentDetailResponseSchema,
  photosListResponseSchema,
  photoDetailResponseSchema,
  caseScopedParamsSchema,
  documentParamsSchema,
  photoParamsSchema,
  type Document,
  type DocumentDetail,
  type DocumentVersion,
  type DocumentRegisterResponse,
  type DocumentsListResponse,
  type DocumentDetailResponse,
  type DuplicateSignal,
  type Photo,
  type PhotoRegisterResponse,
  type PhotosListResponse,
  type PhotoDetailResponse,
  type CaseScopedParams,
  type DocumentParams,
  type PhotoParams,
  // document commands
  registerDocumentRequestSchema,
  registerPhotoRequestSchema,
  metadataListQuerySchema,
  type RegisterDocumentRequest,
  type RegisterDocumentRequestInput,
  type RegisterPhotoRequest,
  type RegisterPhotoRequestInput,
  type MetadataListQuery,
} from './v1/documents/index.js'

export {
  // storage routes
  STORAGE_ROOTS_ROUTE,
  CASE_LOCATION_ROUTE,
  CASE_LOCATION_HISTORY_ROUTE,
  // storage dto
  LOCATION_SOURCES,
  LOCATION_VERIFICATION_STATUSES,
  caseLocationHistoryItemSchema,
  caseLocationHistoryResponseSchema,
  caseLocationParamsSchema,
  caseLocationResponseSchema,
  caseLocationSchema,
  locationSourceSchema,
  locationVerificationStatusSchema,
  storageRootSchema,
  storageRootsResponseSchema,
  type CaseLocation,
  type CaseLocationHistoryItem,
  type CaseLocationHistoryResponse,
  type CaseLocationParams,
  type CaseLocationResponse,
  type LocationSource,
  type LocationVerificationStatus,
  type StorageRoot,
  type StorageRootsResponse,
  // storage commands
  caseLocationAssignRequestSchema,
  caseLocationHistoryQuerySchema,
  type CaseLocationAssignRequest,
  type CaseLocationAssignRequestInput,
  type CaseLocationHistoryQuery,
  type CaseLocationHistoryQueryInput,
} from './v1/storage/index.js'

export {
  DOCUMENT_REQUIREMENTS_ROUTE, requirementStatusSchema, canonicalDocumentTypeSchema, relatedDocumentStatusSchema,
  requirementResultSchema, alternativeGroupSchema, documentRequirementsParamsSchema, documentRequirementsResponseSchema,
  type DocumentRequirementsResponse,
} from './v1/document-requirements/index.js'

export {
  // audit routes
  AUDIT_EVENTS_ROUTE,
  // audit query
  MAX_AUDIT_ACTION_LENGTH,
  MAX_AUDIT_ENTITY_TYPE_LENGTH,
  auditActionSchema,
  auditEntityTypeSchema,
  auditEventsQuerySchema,
  type AuditEventsQuery,
  type AuditEventsQueryInput,
  // audit dto
  auditEventSchema,
  auditEventsResponseSchema,
  type AuditEvent,
  type AuditEventsResponse,
} from './v1/audit/index.js'

export {
  AUTH_LOGIN_ROUTE,
  AUTH_LOGOUT_ROUTE,
  AUTH_SESSION_ROUTE,
  MAX_EMAIL_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_PASSWORD_LENGTH,
  ROLE_CODES,
  emailSchema,
  loginRequestSchema,
  passwordSchema,
  roleCodeSchema,
  sessionResponseSchema,
  sessionUserSchema,
  type LoginRequest,
  type RoleCode,
  type SessionResponse,
  type SessionUser,
} from './v1/auth/index.js'

export {
  JSON_SCHEMA_TARGETS,
  buildJsonSchemas,
  type JsonSchemaName,
} from './json-schema.js'

export * from './v1/case-lifecycle/index.js'
export * from './v1/policy-analysis/index.js'
export * from './v1/pdf-text-extractions/index.js'
export * from './v1/policy-ocr/index.js'
export * from './v1/policy-ai/index.js'
export * from './v1/traffic-value-loss/index.js'
export * from './v1/dashboard/index.js'
export * from './v1/case-operations/index.js'
export * from './v1/fees/index.js'
export * from './v1/email-drafts/index.js'
export * from './v1/email-ai/index.js'
export * from './v1/labor/index.js'
export * from './v1/labor-ai/index.js'
export * from './v1/pert/index.js'
export * from './v1/labor-dictionary/index.js'
