export {
  // primitives
  MAX_ID_LENGTH,
  MAX_PLATE_LENGTH,
  MAX_REFERENCE_NUMBER_LENGTH,
  caseIdSchema,
  caseStageSchema,
  caseStatusSchema,
  caseTypeSchema,
  entityVersionSchema,
  idSchema,
  insurerClaimNumberSchema,
  insurerIdSchema,
  localDateSchema,
  nonEmptyStringSchema,
  notificationFormNumberSchema,
  officeCaseNumberSchema,
  plateNumberSchema,
  serviceIdSchema,
  userIdSchema,
  utcDateTimeSchema,
  type CaseStageDto,
  type CaseStatusDto,
  type CaseTypeDto,
  type EntityVersionDto,
  type LocalDateDto,
  type OfficeCaseNumberDto,
  type PlateNumberDto,
  type UtcDateTimeDto,
  // errors
  API_ERROR_CODES,
  MAX_REPORTED_UNKNOWN_KEYS,
  apiErrorCodeSchema,
  apiErrorSchema,
  fieldErrorSchema,
  zodErrorToApiError,
  type ApiError,
  type ApiErrorCode,
  type FieldError,
  // envelope
  failureEnvelopeSchema,
  responseMetaSchema,
  successEnvelopeSchema,
  type FailureEnvelope,
  type ResponseMeta,
  type SuccessEnvelope,
  // pagination
  DEFAULT_PAGE,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE,
  MAX_PAGE_SIZE,
  SORT_DIRECTIONS,
  SORT_FIELDS,
  pageInfoSchema,
  pageSchema,
  pageSizeSchema,
  pageSizeWithDefaultSchema,
  pageWithDefaultSchema,
  sortDirectionSchema,
  sortFieldSchema,
  type PageInfo,
  type SortDirection,
  type SortField,
  // routes (base)
  API_V1_BASE,
  API_VERSION,
  HEALTH_ROUTE,
} from './common/index.js'

export {
  HEALTH_STATUSES,
  healthResponseSchema,
  healthStatusSchema,
  type HealthResponse,
  type HealthStatus,
} from './health/index.js'

export {
  // cases routes
  CASES_ROUTE,
  CASE_DETAIL_ROUTE,
  // cases query
  MAX_SEARCH_LENGTH,
  casesQuerySchema,
  searchSchema,
  type CasesQuery,
  type CasesQueryInput,
  // cases dto
  caseDetailParamsSchema,
  caseDetailResponseSchema,
  caseDetailSchema,
  caseListItemSchema,
  caseListResponseSchema,
  type CaseDetail,
  type CaseDetailParams,
  type CaseDetailResponse,
  type CaseListItem,
  type CaseListResponse,
  // cases commands
  CASE_UPDATABLE_FIELDS,
  IDEMPOTENCY_KEY_HEADER,
  caseCreateRequestSchema,
  caseUpdateRequestSchema,
  idempotencyKeySchema,
  type CaseCreateRequest,
  type CaseCreateRequestInput,
  type CaseUpdateRequest,
  // cases mappers
  caseCoreToDetail,
  caseCoreToListItem,
  caseDetailToCaseCore,
} from './v1/cases/index.js'

export {
  AUTH_LOGIN_ROUTE,
  AUTH_LOGOUT_ROUTE,
  AUTH_SESSION_ROUTE,
  MAX_EMAIL_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_PASSWORD_LENGTH,
  ROLE_CODES,
  emailSchema,
  loginRequestSchema,
  passwordSchema,
  roleCodeSchema,
  sessionResponseSchema,
  sessionUserSchema,
  type LoginRequest,
  type RoleCode,
  type SessionResponse,
  type SessionUser,
} from './v1/auth/index.js'

export {
  JSON_SCHEMA_TARGETS,
  buildJsonSchemas,
  type JsonSchemaName,
} from './json-schema.js'
