export { parseV1TakipJson, v1TakipJsonV1Schema, type V1TakipJsonParseResult, type V1TakipJsonV1 } from './schema.js'
export {
  applyV1Import,
  discoverV1Folders,
  planV1Import,
  readV1Sidecar,
  type V1DiscoveredFolder,
  type V1FieldBackfillPlanItem,
  type V1ImportAction,
  type V1ImportApplyOutcome,
  type V1ImportApplyResult,
  type V1ImportPlan,
  type V1ImportPlanEntry,
  type V1ImportPlanSummary,
  type V1NamedAssignment,
  type V1NotePlanItem,
  type V1SidecarReadResult,
  type V1TaskPlanItem,
} from './store.js'
export {
  V1_REMEDIATION_MAPPING_VERSION,
  applyV1Remediation,
  planV1Remediation,
  type V1ExplicitResolutionManifest,
  type V1RemediationApplyResult,
  type V1RemediationEntry,
  type V1RemediationFieldItem,
  type V1RemediationNoteItem,
  type V1RemediationOptions,
  type V1RemediationPlan,
  type V1RemediationSummary,
  type V1RemediationTaskItem,
  type V1ResolutionEvidence,
  type V1ResolvedReference,
} from './remediation.js'
