import { z } from 'zod'
import { caseIdSchema, idSchema, utcDateTimeSchema } from '../../common/primitives.js'
export const requirementStatusSchema = z.enum(['required', 'present', 'missing', 'not_applicable', 'control_required'])
export const canonicalDocumentTypeSchema = z.enum(['victim_traffic_policy','insured_traffic_policy','sbm_heavy_damage_result','victim_registration','insured_registration','victim_driver_license','insured_driver_license','casco_policy','casco_vehicle_registration','casco_driver_license','accident_report','ktt','statement','tramer_result','opposing_vehicle_registration','opposing_driver_license','opposing_traffic_policy','fault_ratio'])
export const relatedDocumentStatusSchema = z.strictObject({ documentId: idSchema, status: z.enum(['pending','ready','failed','missing']) })
export const requirementResultSchema = z.strictObject({ requirementCode: z.string().min(1).max(100), canonicalDocumentType: canonicalDocumentTypeSchema, status: requirementStatusSchema, reason: z.string().min(1).max(500), ruleVersion: z.string().min(1).max(64), sourceRule: z.string().min(1).max(100), matchedDocumentIds: z.array(idSchema), relatedDocumentStatuses: z.array(relatedDocumentStatusSchema), evaluatedAt: utcDateTimeSchema, requiresHumanReview: z.boolean() })
export const alternativeGroupSchema = z.strictObject({ groupCode: z.string().min(1).max(100), operator: z.enum(['all_of','any_of','exactly_one']), status: requirementStatusSchema, reason: z.string().min(1).max(500), memberRequirementCodes: z.array(z.string().min(1)), matchedDocumentIds: z.array(idSchema), requiresHumanReview: z.boolean() })
export const documentRequirementsParamsSchema = z.strictObject({ caseId: caseIdSchema })
export const documentRequirementsResponseSchema = z.strictObject({ caseId: caseIdSchema, caseType: z.enum(['traffic','casco']), ruleSetVersion: z.string().min(1).max(64), overallStatus: requirementStatusSchema, requirements: z.array(requirementResultSchema), alternativeGroups: z.array(alternativeGroupSchema), missingCount: z.number().int().min(0), controlRequiredCount: z.number().int().min(0), evaluatedAt: utcDateTimeSchema })
export type DocumentRequirementsResponse = z.infer<typeof documentRequirementsResponseSchema>
