import{afterEach,describe,expect,it,vi}from'vitest'
import{render,screen,waitFor}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import{PolicyAnalysisApiModule}from'./PolicyAnalysisApiModule'
const CASE='019f6000-0000-7000-8000-000000000023',ANALYSIS='019f6000-0000-7000-8000-000000000024',DOC='019f6000-0000-7000-8000-000000000025',VERSION='019f6000-0000-7000-8000-000000000026',SOURCE='019f6000-0000-7000-8000-000000000027'
const source={id:SOURCE,documentId:DOC,documentVersionId:VERSION,pageNumber:5,sectionHeading:'Özel Şartlar',clauseIdentifier:'M-5',rawExcerpt:'Anlaşmasız serviste sentetik koşullu muafiyet.',excerptHash:'a'.repeat(64),locator:null,sourceType:'special_conditions',confidence:.9}
const item={id:ANALYSIS,currentAnalysisVersion:1,currentStatus:'approved',version:2,currentVersion:{sourceDocumentId:DOC,sourceDocumentVersionId:VERSION,analysisVersion:1,analysisStatus:'approved',sourceCompleteness:'complete',humanApprovalStatus:'approved',productName:'Sentetik Kasko',insurerFormat:'v1',sourceReferences:[source],coverages:[{id:'cov',code:'COLLISION',canonicalType:'collision',originalHeading:'Çarpışma',originalWording:'Çarpışma teminat kapsamındadır.',inclusion:'included',sourceReferenceIds:[SOURCE],confidence:.9}],deductibles:[{id:'ded',code:'SERVICE_20',type:'uncontracted_service',trigger:'Anlaşmasız servis',calculationType:'percentage',fixedAmount:null,percentage:20,insuredShare:20,insurerShare:80,approvalStatus:'approved',sourceReferenceIds:[SOURCE],confidence:.9}],serviceRules:[{id:'service',code:'SERVICE',authorizedServiceRequirement:false,insurerContractedServiceRequirement:true,serviceFreedom:'conditional',condition:'Anlaşma aranır.',glassNetwork:null,mobileRepairRestriction:null,miniRepairRestriction:null,sourceReferenceIds:[SOURCE],confidence:.9}],partRules:[{id:'part',code:'PART',allowedPartTypes:['original'],procurementRule:'Orijinal parça.',bettermentCondition:null,sourceReferenceIds:[SOURCE],confidence:.9}],replacementVehicleRules:[{id:'replacement',code:'CAR',available:'conditional',vehicleClass:'C',maximumDays:7,eventLimit:1,serviceCondition:'Anlaşmalı servis',sourceReferenceIds:[SOURCE],confidence:.9}],exclusions:[{id:'ex',code:'RACE',originalWording:'Yarış kapsam dışı.',trigger:'Yarış',affectedCoverage:'collision',sourceReferenceIds:[SOURCE],confidence:.9}],conflicts:[{id:'conf',affectedTopic:'service',explanation:'Poliçe ve zeyil farklı.',severity:'high',resolutionStatus:'open',sourceAId:SOURCE,sourceBId:SOURCE}]}}
const evaluation={result:'conditional',reasoning:['Anlaşmasız servis şartı eşleşti.'],deductibles:item.currentVersion.deductibles,limit:null,insuredShare:20,insurerShare:80,serviceCondition:['Anlaşmalı servis'],partCondition:['Orijinal parça'],requiredAction:['Kontrol et'],requiredDocuments:[],sourceReferences:[source],conflicts:[],missingInformation:[],confidence:.9,humanApprovalRequired:true,policyAnalysisVersion:1,ruleVersion:'2026.07.14.1',operationalRecommendation:{procurementStatus:'pause',mobileRepairStatus:'pause',approvalRequired:true}}
function response(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})}
afterEach(()=>vi.restoreAllMocks())
describe('Kasko police analiz API gorunumu',()=>{
  it('surum, onay, teminat, muafiyet, kaynak sayfa/madde ve conflict gosterir; senaryo calistirir',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==='POST')return response(200,{evaluation});if(url.endsWith('/policy-analyses'))return response(200,{items:[{id:ANALYSIS}]});return response(200,{analysis:item})})as never);const user=userEvent.setup();render(<PolicyAnalysisApiModule caseId={CASE} source="api"/>);expect(screen.getByRole('status')).toHaveTextContent('yükleniyor');await waitFor(()=>expect(screen.getByRole('heading',{name:'Kasko Poliçe Analizi'})).toBeInTheDocument());expect(screen.getByText('Analiz v1')).toBeInTheDocument();expect(screen.getAllByText('Onaylı').length).toBeGreaterThan(0);expect(screen.getByText('Çarpışma teminat kapsamındadır.')).toBeInTheDocument();expect(screen.getAllByText(/Sayfa 5 · Özel Şartlar/).length).toBeGreaterThan(0);expect(screen.getAllByText(/M-5/).length).toBeGreaterThan(0);expect(screen.getByText('Poliçe ve zeyil farklı.')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Değerlendir/}));await waitFor(()=>expect(screen.getByText('Anlaşmasız servis şartı eşleşti.')).toBeInTheDocument());expect(screen.getByText('SERVICE_20')).toBeInTheDocument();expect(document.body.textContent).not.toContain('P:\\')})
  it.each([[401,'Oturum gerekli'],[403,'Yetki yetersiz'],[404,'Dosya bulunamadı']]as const)('HTTP %s durumunda mock fallback yapmaz',async(status,label)=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(response(status,{}));render(<PolicyAnalysisApiModule caseId={CASE} source="api"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent(label));expect(screen.queryByText('Sentetik Kasko')).not.toBeInTheDocument()})
  it('ag hatasini yeniden denemeyle gosterir',async()=>{vi.spyOn(globalThis,'fetch').mockRejectedValue(new TypeError('network'));render(<PolicyAnalysisApiModule caseId={CASE} source="api"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Bağlantı kurulamadı'));expect(screen.getByRole('button',{name:'Yeniden dene'})).toBeInTheDocument()})
  it('gercek bos listeyi ayri bos durumunda gosterir',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(response(200,{items:[]}));render(<PolicyAnalysisApiModule caseId={CASE} source="api"/>);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Kasko poliçe analizi yok'))})
})
