import { AlertTriangle, BookOpenCheck, CheckCircle2, RefreshCw, Scale, ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { usePolicyAnalysis, type DataSourceKind, type PolicyScenarioType, type PolicySourceReferenceRecord } from '../../data'

const STATUS: Record<string, string> = { draft:'Taslak',extracted:'Çıkarıldı',control_required:'Kontrol gerekli',conflict_detected:'Çelişki bulundu',awaiting_approval:'Onay bekliyor',approved:'Onaylı',superseded:'Eski sürüm',rejected:'Reddedildi',failed:'Başarısız',included:'Dahil',excluded:'Hariç',conditional:'Koşullu',unknown:'Bilinmiyor',covered:'Kapsamda' }
const SCENARIOS: readonly { value: PolicyScenarioType; label: string }[] = [
  {value:'coverage',label:'Hasar teminat kapsamında mı?'},{value:'deductible',label:'Muafiyet / tenzil var mı?'},{value:'uncontracted_service',label:'Anlaşmasız servis kesintisi'},{value:'authorized_service',label:'Yetkili servis şartı'},{value:'glass_service',label:'Cam servisi şartı'},{value:'mini_repair',label:'Mini onarım uygunluğu'},{value:'mobile_repair',label:'Mobil onarım uygunluğu'},{value:'replacement_vehicle',label:'İkame araç'},{value:'roadside_assistance',label:'Çekici / yol yardım'},{value:'part_type',label:'Parça tipi şartı'},{value:'betterment',label:'Değer artışı kesintisi'},{value:'previous_total_loss',label:'Önceki tam hasar şartı'},
]
function pct(value:number){return `%${Math.round(value*100)}`}
const AI_FACT_CATEGORY:Record<string,string>={policy_identity:'Poliçe kimliği',coverage:'Teminat',deductible:'Muafiyet',service_rule:'Servis kuralı',part_rule:'Parça kuralı',replacement_vehicle:'İkame araç',assistance:'Yol yardım',valuation:'Değerleme',exclusion:'İstisna',required_document:'Gerekli belge',special_condition:'Özel şart'}
function Sources({items,ids}:{items:readonly PolicySourceReferenceRecord[];ids?:readonly string[]}){const shown=ids===undefined?items:items.filter(item=>ids.includes(item.id));return <div className="policy-sources">{shown.map(source=><article key={source.id}><div><strong>Sayfa {source.pageNumber} · {source.sectionHeading}</strong><span>{source.clauseIdentifier} · güven {pct(source.confidence)}</span></div><q>{source.rawExcerpt}</q></article>)}</div>}
function State({status,retry}:{status:string;retry:()=>void}){const text=status==='loading'?['Poliçe analizi yükleniyor…','Kaynaklı analiz ve sürüm okunuyor.']:status==='empty'?['Kasko poliçe analizi yok','Bu vaka için kontrollü import edilmiş bir analiz sürümü bulunmuyor.']:status==='unauthorized'?['Oturum gerekli','Gerçek poliçe analizini görmek için yeniden giriş yapın.']:status==='forbidden'?['Yetki yetersiz','Bu işlem mevcut rolünüz için izinli değil.']:status==='not_found'?['Dosya bulunamadı','Vaka veya analiz organizasyon kapsamınızda değil.']:status==='conflict'?['Sürüm çakışması','Analiz değişti; güncel sürümü yeniden yükleyin.']:['Bağlantı kurulamadı','Poliçe analiz API’sine erişilemiyor; mock sonuç gösterilmedi.'];return <div className="document-module-state policy-module-state" role={status==='loading'?'status':'alert'}>{status==='loading'?<RefreshCw className="state-view__spinner"/>:<ShieldAlert/>}<strong>{text[0]}</strong><span>{text[1]}</span>{(status==='unavailable'||status==='conflict')&&<button className="button button--secondary" type="button" onClick={retry}>Yeniden dene</button>}</div>}

export function PolicyAnalysisApiModule({caseId,source}:{caseId:string;source:DataSourceKind}) {
  const {data,status,evaluation,evaluating,evaluate,retry}=usePolicyAnalysis(caseId,source,true)
  const [scenario,setScenario]=useState<PolicyScenarioType>('coverage')
  if(status!=='ok'||data===null)return <State status={status==='idle'?'loading':status} retry={retry}/>
  const v=data.currentVersion
  return <section className="policy-analysis-module" aria-labelledby="policy-analysis-heading">
    <header><div><span className="eyebrow">Kanıtlı Kasko analizi</span><h2 id="policy-analysis-heading">Kasko Poliçe Analizi</h2><p>Yalnız doğrulanmış metadata’ya bağlı, kaynaklı ve sürümlü sonuç.</p></div><div className="policy-version"><span>Analiz v{v.analysisVersion}</span><strong>{STATUS[v.analysisStatus]??v.analysisStatus}</strong></div></header>
    <div className="policy-summary-grid"><div><span>Kaynak belge</span><strong className="mono">{v.sourceDocumentId}</strong></div><div><span>Belge sürümü</span><strong className="mono">{v.sourceDocumentVersionId}</strong></div><div><span>Kaynak tamlığı</span><strong>{v.sourceCompleteness==='complete'?'Tam':v.sourceCompleteness==='partial'?'Kısmi':'Bilinmiyor'}</strong></div><div><span>İnsan onayı</span><strong>{v.humanApprovalStatus==='approved'?'Onaylı':v.humanApprovalStatus==='rejected'?'Reddedildi':'Bekliyor'}</strong></div><div><span>Ürün / format</span><strong>{v.productName??'—'} · {v.insurerFormat??'—'}</strong></div></div>
    {v.aiCandidateFacts.length>0&&<section className="policy-ai-promoted" aria-labelledby="policy-ai-promoted-heading"><header><div><span className="eyebrow">Paket 27 · insan incelemesi</span><h3 id="policy-ai-promoted-heading">İnsan Onaylı AI Adayları</h3></div><span>{v.aiCandidateFacts.length} taslak gerçek</span></header><p>Bu kayıtlar kaynak kanıtları korunarak yeni analiz sürümüne aktarılmıştır; analiz onayı yerine geçmez.</p><div>{v.aiCandidateFacts.map(fact=><article key={fact.id}><div><strong>{AI_FACT_CATEGORY[fact.category]??fact.category} · {fact.canonicalField}</strong><span className={`status-pill status-pill--${fact.reviewAction==='edited'?'review':'open'}`}>{fact.reviewAction==='edited'?'Düzenlenerek kabul':'Kabul edildi'}</span></div><p>{fact.originalValue}</p>{(fact.conditions.length>0||fact.exceptions.length>0)&&<small>{fact.conditions.length>0?`Koşullar: ${fact.conditions.join(' · ')}`:''}{fact.conditions.length>0&&fact.exceptions.length>0?' — ':''}{fact.exceptions.length>0?`İstisnalar: ${fact.exceptions.join(' · ')}`:''}</small>}<Sources items={v.sourceReferences} ids={fact.sourceReferenceIds}/></article>)}</div></section>}
    <div className="policy-analysis-grid">
      <section className="policy-facts"><h3>Teminatlar</h3>{v.coverages.length===0?<p className="policy-empty">Kayıt yok.</p>:v.coverages.map(item=><article key={item.id}><div><strong>{item.originalHeading}</strong><span className={`status-pill status-pill--${item.inclusion==='included'?'open':item.inclusion==='excluded'?'late':'review'}`}>{STATUS[item.inclusion]??item.inclusion}</span></div><p>{item.originalWording}</p><Sources items={v.sourceReferences} ids={item.sourceReferenceIds}/></article>)}</section>
      <section className="policy-facts"><h3>Muafiyet ve Tenziller</h3>{v.deductibles.length===0?<p className="policy-empty">Kayıt yok.</p>:v.deductibles.map(item=><article key={item.id}><div><strong>{item.trigger}</strong><span>{item.percentage!==null?`%${item.percentage}`:item.fixedAmount!==null?`${item.fixedAmount} TL`:'Koşullu'}</span></div><p>{item.insuredShare!==null?`Sigortalı payı %${item.insuredShare}. `:''}{item.approvalStatus==='approved'?'Madde kontrol edildi.':'Madde ayrıca onay gerektiriyor.'}</p><Sources items={v.sourceReferences} ids={item.sourceReferenceIds}/></article>)}</section>
      <section className="policy-facts"><h3>Servis ve Parça Kuralları</h3>{v.serviceRules.map(item=><article key={item.id}><strong>{item.code}</strong><p>{item.condition??'Koşul metni belirtilmedi.'} {item.insurerContractedServiceRequirement===true?'Sigortacıya özel anlaşma aranır.':''}</p><Sources items={v.sourceReferences} ids={item.sourceReferenceIds}/></article>)}{v.partRules.map(item=><article key={item.id}><strong>{item.allowedPartTypes.join(' / ')}</strong><p>{item.procurementRule??item.bettermentCondition??'Parça koşulu belirtilmedi.'}</p><Sources items={v.sourceReferences} ids={item.sourceReferenceIds}/></article>)}</section>
      <section className="policy-facts"><h3>İkame Araç ve İstisnalar</h3>{v.replacementVehicleRules.map(item=><article key={item.id}><div><strong>İkame araç · {STATUS[item.available]??item.available}</strong><span>{item.maximumDays===null?'—':`${item.maximumDays} gün`}</span></div><p>{item.serviceCondition??'Servis koşulu belirtilmedi.'}</p></article>)}{v.exclusions.map(item=><article key={item.id}><strong>{item.trigger}</strong><p>{item.originalWording}</p><Sources items={v.sourceReferences} ids={item.sourceReferenceIds}/></article>)}</section>
    </div>
    <section className="policy-conflicts"><h3><AlertTriangle size={15}/> Açık Çelişkiler</h3>{v.conflicts.length===0?<p><CheckCircle2 size={14}/> Açık çelişki yok.</p>:v.conflicts.map(item=><article key={item.id}><strong>{item.affectedTopic} · {item.severity}</strong><span>{item.explanation}</span><em>{STATUS[item.resolutionStatus]??item.resolutionStatus}</em></article>)}</section>
    <section className="policy-scenario"><header><div><h3><Scale size={15}/> Senaryo Değerlendirmesi</h3><p>Sonuç oran/tutar tahmin etmez; yalnız kanıtlı kuralları uygular.</p></div><div className="policy-scenario__controls"><label><span>Senaryo</span><select value={scenario} onChange={event=>setScenario(event.target.value as PolicyScenarioType)}>{SCENARIOS.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select></label><button className="button button--primary" type="button" disabled={evaluating} onClick={()=>void evaluate(scenario)}>{evaluating?<RefreshCw className="state-view__spinner" size={14}/>:<BookOpenCheck size={14}/>} Değerlendir</button></div></header>
      {evaluation&&<div className="policy-result" aria-live="polite"><div className="policy-result__headline"><strong>{STATUS[evaluation.result]??evaluation.result}</strong><span>Kural {evaluation.ruleVersion} · güven {pct(evaluation.confidence)}</span></div><ul>{evaluation.reasoning.map(reason=><li key={reason}>{reason}</li>)}{evaluation.missingInformation.map(info=><li className="text-warning" key={info}>{info}</li>)}</ul><dl><div><dt>Tedarik</dt><dd>{evaluation.operationalRecommendation.procurementStatus}</dd></div><div><dt>Mobil onarım</dt><dd>{evaluation.operationalRecommendation.mobileRepairStatus}</dd></div><div><dt>İnsan onayı</dt><dd>{evaluation.humanApprovalRequired?'Gerekli':'Gerekli değil'}</dd></div><div><dt>Muafiyet</dt><dd>{evaluation.deductibles.map(item=>item.code).join(', ')||'Yok'}</dd></div></dl><Sources items={evaluation.sourceReferences}/></div>}
    </section>
  </section>
}
