import type {FastifyInstance,FastifyReply,FastifyRequest} from 'fastify'
import type pg from 'pg'
import {IDEMPOTENCY_KEY_HEADER,POLICY_AI_CANCEL_ROUTE,POLICY_AI_CANCEL_SCOPE,POLICY_AI_CANDIDATES_ROUTE,POLICY_AI_CANDIDATE_REVIEW_ROUTE,POLICY_AI_CANDIDATE_REVIEW_SCOPE,POLICY_AI_EXTRACTIONS_ROUTE,POLICY_AI_PLAN_ROUTE,POLICY_AI_PLAN_SCOPE,POLICY_AI_PROMOTE_ROUTE,POLICY_AI_PROMOTE_SCOPE,POLICY_AI_PROMOTION_PREVIEW_ROUTE,POLICY_AI_RUN_ROUTE,POLICY_AI_START_ROUTE,POLICY_AI_START_SCOPE,POLICY_AI_USAGE_ROUTE,failureEnvelopeSchema,idempotencyKeySchema,policyAiCancelRequestSchema,policyAiCandidateParamsSchema,policyAiCandidateReviewRequestSchema,policyAiCandidateReviewResponseSchema,policyAiCandidatesResponseSchema,policyAiCaseParamsSchema,policyAiListQuerySchema,policyAiPlanRequestSchema,policyAiPromotionPreviewResponseSchema,policyAiPromotionRequestSchema,policyAiPromotionResponseSchema,policyAiRunParamsSchema,policyAiRunResponseSchema,policyAiRunsResponseSchema,policyAiStartRequestSchema,policyAiUsageQuerySchema,policyAiUsageResponseSchema,zodErrorToApiError} from '@hasarbotu/contracts'
import {requireAnyRole,requireSession} from '../auth/guard.js'
import {createAuthStore} from '../auth/store.js'
import {hashRequestBody,isIdempotencyRace} from '../db/idempotency.js'
import {failureBody} from '../errors/failure.js'
import type {PolicyAiProviderRegistry} from './providers.js'
import {createPolicyAiReviewStore,PolicyAiReviewStoreError} from './review-store.js'
import {createPolicyAiStore,PolicyAiStoreError} from './store.js'

const WRITE_ROLES=['admin','expert','case_manager'] as const,USAGE_ROLES=['admin','expert'] as const
const idempotencyKey=(request:FastifyRequest)=>{const raw=request.headers[IDEMPOTENCY_KEY_HEADER];const parsed=idempotencyKeySchema.safeParse(Array.isArray(raw)?raw[0]:raw);return parsed.success?parsed.data:undefined}
const keyRequired=(reply:FastifyReply,requestId:string)=>reply.code(400).send(failureEnvelopeSchema.parse({ok:false,error:{code:'validation_error',message:'Request validation failed.',fieldErrors:[{path:IDEMPOTENCY_KEY_HEADER,code:'idempotency_key_required',message:'Field value is not allowed.'}],requestId}}))
function safeError(reply:FastifyReply,requestId:string,error:PolicyAiStoreError){if(error.code==='not_found')return reply.code(404).send(failureBody('not_found','AI extraction not found.',requestId));if(error.code==='wrong_case_type'||error.code==='invalid_source')return reply.code(400).send(failureBody('ai_evidence_invalid','AI extraction source is not eligible.',requestId));if(error.code==='version_conflict')return reply.code(409).send(failureBody('ai_extraction_stale','AI extraction version changed.',requestId));if(error.code==='idempotency_conflict')return reply.code(409).send(failureBody('idempotency_conflict','Idempotency key was used with a different request.',requestId));return reply.code(409).send(failureBody('ai_extraction_conflict','AI extraction state does not permit this operation.',requestId))}
function safeReviewError(reply:FastifyReply,requestId:string,error:PolicyAiReviewStoreError){
  if(error.code==='not_found')return reply.code(404).send(failureBody('not_found','AI candidate or extraction not found.',requestId))
  if(error.code==='idempotency_conflict')return reply.code(409).send(failureBody('idempotency_conflict','Idempotency key was used with a different request.',requestId))
  if(error.code==='review_stale')return reply.code(409).send(failureBody('ai_candidate_review_stale','Candidate review version changed.',requestId))
  if(error.code==='review_conflict')return reply.code(409).send(failureBody('ai_candidate_review_conflict','Candidate evidence does not permit this review decision.',requestId))
  if(error.code==='promotion_stale')return reply.code(409).send(failureBody('ai_candidate_promotion_stale','Promotion preview is stale.',requestId))
  if(error.code==='promotion_blocked')return reply.code(409).send(failureBody('ai_candidate_promotion_blocked','Candidate promotion requirements are not satisfied.',requestId))
  return reply.code(409).send(failureBody('ai_extraction_conflict','AI extraction state does not permit this operation.',requestId))
}
function validation(reply:FastifyReply,requestId:string,error:import('zod').ZodError|undefined){if(error===undefined)throw new Error('validation_error_missing');return reply.code(400).send(failureEnvelopeSchema.parse({ok:false,error:zodErrorToApiError(error,requestId)}))}
function isPolicyAiCreationRace(error:unknown){const pgError=error as {code?:string;constraint?:string};return isIdempotencyRace(error)||(pgError.code==='23505'&&['ai_source_bundles_hash_unique','ai_extraction_runs_identity_unique'].includes(pgError.constraint??''))}

export function registerPolicyAiRoutes(app:FastifyInstance,options:{readonly pool:pg.Pool;readonly providers:PolicyAiProviderRegistry}){const auth=createAuthStore(options.pool),store=createPolicyAiStore(options.pool,options.providers),reviewStore=createPolicyAiReviewStore(options.pool)
  app.post(POLICY_AI_PLAN_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireAnyRole(auth,request,reply,WRITE_ROLES);if(session===undefined)return;const params=policyAiCaseParamsSchema.safeParse(request.params),body=policyAiPlanRequestSchema.safeParse(request.body);if(!params.success||!body.success)return validation(reply,requestId,!params.success?params.error:body.error);const key=idempotencyKey(request);if(key===undefined)return keyRequired(reply,requestId);const run=()=>store.plan({organizationId:session.user.organizationId,actorUserId:session.user.id,requestId},params.data.caseId,body.data,{scope:POLICY_AI_PLAN_SCOPE,key,requestHash:hashRequestBody({params:params.data,body:body.data})});try{let result;try{result=await run()}catch(error){if(!isPolicyAiCreationRace(error))throw error;result=await run()}return reply.code(result.status).send(policyAiRunResponseSchema.parse(result.body))}catch(error){if(error instanceof PolicyAiStoreError)return safeError(reply,requestId,error);throw error}})
  app.post(POLICY_AI_START_ROUTE,async(request,reply)=>command(request,reply,'start'))
  app.post(POLICY_AI_CANCEL_ROUTE,async(request,reply)=>command(request,reply,'cancel'))
  async function command(request:FastifyRequest,reply:FastifyReply,kind:'start'|'cancel'){const requestId=String(request.id),session=await requireAnyRole(auth,request,reply,WRITE_ROLES);if(session===undefined)return;const params=policyAiRunParamsSchema.safeParse(request.params),body=(kind==='start'?policyAiStartRequestSchema:policyAiCancelRequestSchema).safeParse(request.body);if(!params.success||!body.success)return validation(reply,requestId,!params.success?params.error:body.error);const key=idempotencyKey(request);if(key===undefined)return keyRequired(reply,requestId);try{const actor={organizationId:session.user.organizationId,actorUserId:session.user.id,requestId},idem={scope:kind==='start'?POLICY_AI_START_SCOPE:POLICY_AI_CANCEL_SCOPE,key,requestHash:hashRequestBody({params:params.data,body:body.data})};let result;if(kind==='start'){const start=policyAiStartRequestSchema.parse(body.data);result=await store.start(actor,params.data.caseId,params.data.runId,start.expectedVersion,start.expectedSourceBundleHash,idem)}else{const cancel=policyAiCancelRequestSchema.parse(body.data);result=await store.cancel(actor,params.data.caseId,params.data.runId,cancel.expectedVersion,idem)}return reply.code(result.status).send(policyAiRunResponseSchema.parse(result.body))}catch(error){if(error instanceof PolicyAiStoreError)return safeError(reply,requestId,error);throw error}}
  app.get(POLICY_AI_EXTRACTIONS_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireSession(auth,request,reply);if(session===undefined)return;const params=policyAiCaseParamsSchema.safeParse(request.params),query=policyAiListQuerySchema.safeParse(request.query);if(!params.success||!query.success)return validation(reply,requestId,!params.success?params.error:query.error);const runs=await store.list(session.user.organizationId,params.data.caseId,query.data.page,query.data.pageSize);if(runs===undefined)return reply.code(404).send(failureBody('not_found','Case not found.',requestId));return policyAiRunsResponseSchema.parse({items:runs.map(run=>{const summary={...run};Reflect.deleteProperty(summary,'bundle');Reflect.deleteProperty(summary,'budget');return summary})})})
  app.get(POLICY_AI_RUN_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireSession(auth,request,reply);if(session===undefined)return;const params=policyAiRunParamsSchema.safeParse(request.params);if(!params.success)return validation(reply,requestId,params.error);const run=await store.get(session.user.organizationId,params.data.caseId,params.data.runId);if(run===undefined)return reply.code(404).send(failureBody('not_found','AI extraction not found.',requestId));return policyAiRunResponseSchema.parse({run})})
  app.get(POLICY_AI_CANDIDATES_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireSession(auth,request,reply);if(session===undefined)return;const params=policyAiRunParamsSchema.safeParse(request.params),query=policyAiListQuerySchema.safeParse(request.query);if(!params.success||!query.success)return validation(reply,requestId,!params.success?params.error:query.error);const value=await store.candidates(session.user.organizationId,params.data.caseId,params.data.runId,query.data.page,query.data.pageSize);if(value===undefined)return reply.code(404).send(failureBody('not_found','AI extraction not found.',requestId));const {totalItems,...page}=value;return policyAiCandidatesResponseSchema.parse({...page,pageInfo:{page:query.data.page,pageSize:query.data.pageSize,totalItems,totalPages:totalItems===0?0:Math.ceil(totalItems/query.data.pageSize)}})})
  app.post(POLICY_AI_CANDIDATE_REVIEW_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireAnyRole(auth,request,reply,WRITE_ROLES);if(session===undefined)return;const params=policyAiCandidateParamsSchema.safeParse(request.params),body=policyAiCandidateReviewRequestSchema.safeParse(request.body);if(!params.success||!body.success)return validation(reply,requestId,!params.success?params.error:body.error);const key=idempotencyKey(request);if(key===undefined)return keyRequired(reply,requestId);try{const result=await reviewStore.review({organizationId:session.user.organizationId,actorUserId:session.user.id,requestId},params.data.caseId,params.data.runId,params.data.candidateId,body.data,{scope:POLICY_AI_CANDIDATE_REVIEW_SCOPE,key,requestHash:hashRequestBody({params:params.data,body:body.data})});return reply.code(result.status).send(policyAiCandidateReviewResponseSchema.parse(result.body))}catch(error){if(error instanceof PolicyAiReviewStoreError)return safeReviewError(reply,requestId,error);throw error}})
  app.get(POLICY_AI_PROMOTION_PREVIEW_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireSession(auth,request,reply);if(session===undefined)return;const params=policyAiRunParamsSchema.safeParse(request.params);if(!params.success)return validation(reply,requestId,params.error);try{const value=await reviewStore.preview(session.user.organizationId,params.data.caseId,params.data.runId);if(value===undefined)return reply.code(404).send(failureBody('not_found','AI extraction not found.',requestId));return policyAiPromotionPreviewResponseSchema.parse(value)}catch(error){if(error instanceof PolicyAiReviewStoreError)return safeReviewError(reply,requestId,error);throw error}})
  app.post(POLICY_AI_PROMOTE_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireAnyRole(auth,request,reply,WRITE_ROLES);if(session===undefined)return;const params=policyAiRunParamsSchema.safeParse(request.params),body=policyAiPromotionRequestSchema.safeParse(request.body);if(!params.success||!body.success)return validation(reply,requestId,!params.success?params.error:body.error);const key=idempotencyKey(request);if(key===undefined)return keyRequired(reply,requestId);try{const result=await reviewStore.promote({organizationId:session.user.organizationId,actorUserId:session.user.id,requestId},params.data.caseId,params.data.runId,body.data,{scope:POLICY_AI_PROMOTE_SCOPE,key,requestHash:hashRequestBody({params:params.data,body:body.data})});return reply.code(result.status).send(policyAiPromotionResponseSchema.parse(result.body))}catch(error){if(error instanceof PolicyAiReviewStoreError)return safeReviewError(reply,requestId,error);throw error}})
  app.get(POLICY_AI_USAGE_ROUTE,async(request,reply)=>{const requestId=String(request.id),session=await requireAnyRole(auth,request,reply,USAGE_ROLES);if(session===undefined)return;const query=policyAiUsageQuerySchema.safeParse(request.query);if(!query.success)return validation(reply,requestId,query.error);const month=query.data.month??new Date().toISOString().slice(0,7);return policyAiUsageResponseSchema.parse(await store.usage(session.user.organizationId,month))})
}
