import { createReadStream, createWriteStream } from 'node:fs'
import { access, copyFile, lstat, mkdir, mkdtemp, open, rm } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { pipeline } from 'node:stream/promises'
import { Worker } from 'node:worker_threads'
import type { JobPayload, PolicyOcrChunkRequest, PolicyOcrResultSummary } from '@hasarbotu/contracts'
import { POLICY_OCR_LANGUAGE_DATA_HASHES, POLICY_OCR_LANGUAGE_DATA_SIZES, policyOcrLanguageDataHash } from '@hasarbotu/domain'
import { assertRealPathUnderRoot, PathSafetyError, resolveUnderRoot } from './path-resolver.js'
import { streamSha256 } from './verifier.js'
import type { PolicyOcrWorkerInput, PolicyOcrWorkerMessage } from './policy-ocr-protocol.js'

type Payload=Extract<JobPayload,{readonly kind:'policy_ocr'}>
export interface PolicyOcrExtractionResult{readonly outcome:'verified'|'failed';readonly errorCode?:string;readonly policyOcr?:PolicyOcrResultSummary;readonly observedHash?:undefined;readonly observedSize?:undefined}
export interface PolicyOcrExtractorHooks{readonly onChunk:(chunk:PolicyOcrChunkRequest)=>Promise<void>;readonly onHeartbeat?:(phase:'rendering'|'preprocessing'|'recognizing'|'normalizing'|'validating'|'ocr')=>Promise<void>;readonly workerUrl?:URL}

function errno(error:unknown):string|undefined{return(error as NodeJS.ErrnoException).code}
async function workerTarget():Promise<{url:URL;execArgv?:string[]}>{const compiled=new URL('./policy-ocr-worker.js',import.meta.url);try{await access(fileURLToPath(compiled));return{url:compiled}}catch{return{url:new URL('./policy-ocr-worker.ts',import.meta.url),execArgv:['--import','tsx']}}}
async function assertNoReparseComponents(rootAbsolute:string,relativePath:string):Promise<void>{let current=rootAbsolute;for(const component of relativePath.split('/')){current=join(current,component);const metadata=await lstat(current);if(metadata.isSymbolicLink())throw new PathSafetyError('reparse_point_rejected','reparse point is not allowed')}}
function safeError(error:unknown):string{const message=error instanceof Error?error.message:'';if(/^[a-z0-9_]{1,64}$/.test(message))return message;if(error instanceof PathSafetyError)return error.code;if(errno(error)==='ENOENT')return'source_missing';if(errno(error)==='EACCES'||errno(error)==='EPERM')return'access_denied';return'ocr_failed'}

async function copyLanguageAssets(directory:string,payload:Payload):Promise<void>{if(payload.languageDataHash!==policyOcrLanguageDataHash(payload.languageMode))throw new Error('language_asset_hash_mismatch');const require=createRequire(import.meta.url),languages=payload.languageMode==='tur+eng'?['tur','eng'] as const:[payload.languageMode] as const;for(const language of languages){const packageDirectory=dirname(require.resolve(`@tesseract.js-data/${language}/package.json`)),source=join(packageDirectory,'4.0.0',`${language}.traineddata.gz`);let observed;try{observed=await streamSha256(source)}catch{throw new Error('language_asset_missing')}if(observed.hash!==POLICY_OCR_LANGUAGE_DATA_HASHES[language]||observed.size!==POLICY_OCR_LANGUAGE_DATA_SIZES[language])throw new Error('language_asset_hash_mismatch');await copyFile(source,join(directory,`${language}.traineddata.gz`))}}

async function isolated(input:PolicyOcrWorkerInput,payload:Payload,hooks:PolicyOcrExtractorHooks):Promise<PolicyOcrResultSummary>{const target=hooks.workerUrl===undefined?await workerTarget():{url:hooks.workerUrl};return new Promise((resolvePromise,rejectPromise)=>{const worker=new Worker(target.url,{workerData:input,...(target.execArgv===undefined?{}:{execArgv:target.execArgv}),resourceLimits:{maxOldGenerationSizeMb:payload.workerMemoryMb,maxYoungGenerationSizeMb:64,stackSizeMb:8},name:`policy-ocr-${payload.ocrRunId}`});let sequence=0,settled=false,uploads=Promise.resolve();const reject=async(error:Error)=>{if(settled)return;settled=true;clearTimeout(timeout);await worker.terminate().catch(()=>undefined);rejectPromise(error)},resolve=async(summary:PolicyOcrResultSummary)=>{if(settled)return;settled=true;clearTimeout(timeout);await worker.terminate().catch(()=>undefined);resolvePromise(summary)},timeout=setTimeout(()=>void reject(new Error('ocr_timeout')),payload.timeoutMs);worker.on('message',(message:PolicyOcrWorkerMessage)=>{if(settled)return;if(message.kind==='phase'){uploads=uploads.then(async()=>hooks.onHeartbeat?.(message.phase));uploads.catch(()=>void reject(new Error('heartbeat_failed')));return}if(message.kind==='page'){const chunk:PolicyOcrChunkRequest={ocrRunId:payload.ocrRunId,ocrRunVersion:payload.ocrRunVersion,sequence,pages:[message.page]};sequence+=1;uploads=uploads.then(async()=>{await hooks.onHeartbeat?.('ocr');await hooks.onChunk(chunk)});uploads.catch(()=>void reject(new Error('chunk_upload_failed')));return}if(message.kind==='error'){void reject(new Error(message.errorCode));return}void uploads.then(()=>resolve(message.summary)).catch(()=>reject(new Error('chunk_upload_failed')))});worker.on('error',()=>void reject(new Error('worker_crashed')));worker.on('exit',code=>{if(settled||code===0)return;settled=true;clearTimeout(timeout);rejectPromise(new Error('worker_crashed'))})})}

export async function extractPolicyOcr(rootAbsolute:string,payload:Payload,hooks:PolicyOcrExtractorHooks):Promise<PolicyOcrExtractionResult>{let temporaryDirectory:string|undefined;try{if(payload.engineVersion!=='7.0.0')return{outcome:'failed',errorCode:'engine_version_mismatch'};const candidate=resolveUnderRoot(rootAbsolute,payload.relativePath);await assertNoReparseComponents(rootAbsolute,payload.relativePath);const realSource=await assertRealPathUnderRoot(rootAbsolute,candidate),metadata=await lstat(realSource);if(metadata.isSymbolicLink())return{outcome:'failed',errorCode:'reparse_point_rejected'};if(!metadata.isFile())return{outcome:'failed',errorCode:'not_a_file'};if(metadata.size>payload.maxSourceBytes)return{outcome:'failed',errorCode:'source_size_limit_exceeded'};const observed=await streamSha256(realSource);if(observed.hash!==payload.declaredHash||observed.size!==payload.declaredSize)return{outcome:'failed',errorCode:'source_changed'};const handle=await open(realSource,'r'),magic=Buffer.alloc(5);try{await handle.read(magic,0,magic.length,0)}finally{await handle.close()}if(magic.toString('ascii')!=='%PDF-')return{outcome:'failed',errorCode:'invalid_pdf_magic'}
  temporaryDirectory=await mkdtemp(join(tmpdir(),'hasarbotu-ocr-'));const temporaryPdf=join(temporaryDirectory,'source.pdf'),assetDirectory=join(temporaryDirectory,'assets');await mkdir(assetDirectory);await pipeline(createReadStream(realSource),createWriteStream(temporaryPdf,{flags:'wx'}));const copied=await streamSha256(temporaryPdf);if(copied.hash!==observed.hash||copied.size!==observed.size)return{outcome:'failed',errorCode:'temporary_copy_mismatch'};await copyLanguageAssets(assetDirectory,payload);await hooks.onHeartbeat?.('rendering');const summary=await isolated({filePath:temporaryPdf,languageAssetDirectory:assetDirectory,ocrRunId:payload.ocrRunId,ocrRunVersion:payload.ocrRunVersion,sourceHash:observed.hash,sourceSize:observed.size,languageMode:payload.languageMode,languageDataHash:payload.languageDataHash,renderProfileVersion:payload.renderProfileVersion,qualityVersion:payload.qualityVersion,locatorVersion:payload.locatorVersion,eligiblePages:payload.eligiblePages.map(item=>({textPageId:item.textPageId,pageNumber:item.pageNumber,sourcePageStatus:item.sourcePageStatus})),renderDpi:payload.renderDpi,maxImagePixels:payload.maxImagePixels,maxPageCharacters:payload.maxPageCharacters,maxTotalCharacters:payload.maxTotalCharacters,maxElementsPerPage:payload.maxElementsPerPage},payload,hooks);return{outcome:'verified',policyOcr:summary}
}catch(error){return{outcome:'failed',errorCode:safeError(error)}}finally{if(temporaryDirectory!==undefined)await rm(temporaryDirectory,{recursive:true,force:true}).catch(()=>undefined)}}
